In [2]:
import pandas as pd
import numpy as np

---

### 1. handle missing values

In [3]:
df = pd.read_csv('yearly_sales_2024_2.csv')
df.head(5)

   SaleID CustomerID       Product  Quantity  Price    SaleDate
0       1    CUST043         Mouse       5.0   15.0  07-03-2024
1       2    CUST039    RAM (16GB)       4.0   70.0  29-01-2024
2       3    CUST016  External HDD       3.0   90.0  18-06-2024
3       4    CUST023       Printer       4.0  120.0  08-11-2024
4       5    CUST047        Laptop       5.0  750.0  21-09-2024

##### Drop rows with missing values

In [4]:
df.dropna()

     SaleID CustomerID       Product  Quantity  Price    SaleDate
0         1    CUST043         Mouse       5.0   15.0  07-03-2024
1         2    CUST039    RAM (16GB)       4.0   70.0  29-01-2024
2         3    CUST016  External HDD       3.0   90.0  18-06-2024
3         4    CUST023       Printer       4.0  120.0  08-11-2024
4         5    CUST047        Laptop       5.0  750.0  21-09-2024
..      ...        ...           ...       ...    ...         ...
494     495    CUST038    Smartphone       1.0  500.0  15-05-2024
495     496    CUST016        Laptop       5.0  750.0  09-09-2024
496     497    CUST004  External HDD       1.0   90.0  08-09-2024
497     498    CUST044        Webcam       5.0   35.0  04-03-2024
499     500    CUST048    Laptop Bag       5.0   40.0  13-08-2024

[473 rows x 6 columns]

In [6]:
# Get rows with missing values 

missing_values_data = df[df.isna().any(axis=1)]
missing_values_data

     SaleID CustomerID        Product  Quantity  Price    SaleDate
20       21    CUST011     Smartphone       3.0  500.0         NaN
22       23        NaN      Projector       3.0  600.0  19-12-2024
31       32    CUST028         Webcam       NaN   35.0  14-06-2024
37       38        NaN          Mouse       5.0   15.0  17-12-2024
57       58    CUST050        Monitor       NaN  200.0  12-03-2024
65       66        NaN   Gaming Chair       5.0  220.0  29-02-2024
82       83    CUST049     Laptop Bag       4.0   40.0         NaN
92       93    CUST008            NaN       3.0  250.0  04-03-2024
120     121    CUST014         Webcam       5.0    NaN  15-09-2024
148     149    CUST009         Router       1.0    NaN  04-01-2024
150     151        NaN       Speakers       2.0   45.0  17-07-2024
193     194    CUST021            NaN       4.0   25.0  07-05-2024
196     197    CUST009     Smartwatch       3.0    NaN  04-02-2024
209     210    CUST050   Gaming Chair       3.0  220.0         NaN
216     217    CUST039            NaN       2.0  180.0  24-03-2024
229     230    CUST045     Laptop Bag       NaN   40.0  17-07-2024
239     240        NaN            CPU       5.0  350.0  24-03-2024
241     242    CUST049  Graphics Card       1.0    NaN  22-04-2024
270     271    CUST040            NaN       2.0   25.0  14-05-2024
305     306    CUST024     Headphones       3.0    NaN  22-12-2024
318     319    CUST039            NaN       1.0  180.0  17-07-2024
323     324    CUST013     RAM (16GB)       4.0    NaN  05-05-2024
344     345        NaN      Projector       2.0  600.0  02-10-2024
378     379    CUST001            NaN       3.0  750.0  22-03-2024
467     468    CUST030         Webcam       1.0    NaN  27-04-2024
481     482    CUST033      Projector       2.0  600.0         NaN
498     499    CUST030            NaN       3.0  220.0  27-10-2024

In [11]:
# Get the price of webcam 


webcam_price = df.loc[(df["Product"] == 'Webcam') & (df["Price"].notna()), "Price"].iloc[0]
webcam_price

np.float64(35.0)

In [15]:
# Edit missing values for webcam

df.loc[(df["Product"] == 'Webcam') & (df["Price"].isna()), "Price"] = webcam_price

In [17]:
# Check if Price column of webcam is still empty


df[df.isna().any(axis=1)]

     SaleID CustomerID        Product  Quantity  Price    SaleDate
20       21    CUST011     Smartphone       3.0  500.0         NaN
22       23        NaN      Projector       3.0  600.0  19-12-2024
31       32    CUST028         Webcam       NaN   35.0  14-06-2024
37       38        NaN          Mouse       5.0   15.0  17-12-2024
57       58    CUST050        Monitor       NaN  200.0  12-03-2024
65       66        NaN   Gaming Chair       5.0  220.0  29-02-2024
82       83    CUST049     Laptop Bag       4.0   40.0         NaN
92       93    CUST008            NaN       3.0  250.0  04-03-2024
148     149    CUST009         Router       1.0    NaN  04-01-2024
150     151        NaN       Speakers       2.0   45.0  17-07-2024
193     194    CUST021            NaN       4.0   25.0  07-05-2024
196     197    CUST009     Smartwatch       3.0    NaN  04-02-2024
209     210    CUST050   Gaming Chair       3.0  220.0         NaN
216     217    CUST039            NaN       2.0  180.0  24-03-2024
229     230    CUST045     Laptop Bag       NaN   40.0  17-07-2024
239     240        NaN            CPU       5.0  350.0  24-03-2024
241     242    CUST049  Graphics Card       1.0    NaN  22-04-2024
270     271    CUST040            NaN       2.0   25.0  14-05-2024
305     306    CUST024     Headphones       3.0    NaN  22-12-2024
318     319    CUST039            NaN       1.0  180.0  17-07-2024
323     324    CUST013     RAM (16GB)       4.0    NaN  05-05-2024
344     345        NaN      Projector       2.0  600.0  02-10-2024
378     379    CUST001            NaN       3.0  750.0  22-03-2024
481     482    CUST033      Projector       2.0  600.0         NaN
498     499    CUST030            NaN       3.0  220.0  27-10-2024

In [27]:
# Fill missing value in Quantity column for webcam


df.loc[(df["Product"] == 'Webcam') & (df["Quantity"].isna()), "Quantity"] = \
df.loc[(df["Product"] == 'Webcam') & (df["Quantity"].isna())].apply(lambda row: row["Price"]/webcam_price, axis=1)

In [29]:
# Check if missing Quantity is present for webcam


df[df.isna().any(axis=1)]

     SaleID CustomerID        Product  Quantity  Price    SaleDate
20       21    CUST011     Smartphone       3.0  500.0         NaN
22       23        NaN      Projector       3.0  600.0  19-12-2024
37       38        NaN          Mouse       5.0   15.0  17-12-2024
57       58    CUST050        Monitor       NaN  200.0  12-03-2024
65       66        NaN   Gaming Chair       5.0  220.0  29-02-2024
82       83    CUST049     Laptop Bag       4.0   40.0         NaN
92       93    CUST008            NaN       3.0  250.0  04-03-2024
148     149    CUST009         Router       1.0    NaN  04-01-2024
150     151        NaN       Speakers       2.0   45.0  17-07-2024
193     194    CUST021            NaN       4.0   25.0  07-05-2024
196     197    CUST009     Smartwatch       3.0    NaN  04-02-2024
209     210    CUST050   Gaming Chair       3.0  220.0         NaN
216     217    CUST039            NaN       2.0  180.0  24-03-2024
229     230    CUST045     Laptop Bag       NaN   40.0  17-07-2024
239     240        NaN            CPU       5.0  350.0  24-03-2024
241     242    CUST049  Graphics Card       1.0    NaN  22-04-2024
270     271    CUST040            NaN       2.0   25.0  14-05-2024
305     306    CUST024     Headphones       3.0    NaN  22-12-2024
318     319    CUST039            NaN       1.0  180.0  17-07-2024
323     324    CUST013     RAM (16GB)       4.0    NaN  05-05-2024
344     345        NaN      Projector       2.0  600.0  02-10-2024
378     379    CUST001            NaN       3.0  750.0  22-03-2024
481     482    CUST033      Projector       2.0  600.0         NaN
498     499    CUST030            NaN       3.0  220.0  27-10-2024

In [30]:
# Dynamically change quantity of any product

for idx, row in missing_values_data.iterrows():
    product = row["Product"]
    print(product)

Smartphone
Projector
Webcam
Mouse
Monitor
Gaming Chair
Laptop Bag
nan
Webcam
Router
Speakers
nan
Smartwatch
Gaming Chair
nan
Laptop Bag
CPU
Graphics Card
nan
Headphones
nan
RAM (16GB)
Projector
nan
Webcam
Projector
nan

In [33]:
for idx, row in missing_values_data.iterrows():
    product = row["Product"]
    unit_price_series = df.loc[(df["Product"] == product) & (df["Price"].notna()), "Price"].iloc[0]
    print(unit_price_series)

500.0
600.0
35.0
15.0
200.0
220.0
40.0

IndexError: single positional indexer is out-of-bounds

In [35]:
for idx, row in missing_values_data.iterrows():
    product = row["Product"]
    unit_price_series = df.loc[(df["Product"] == product) & (df["Price"].notna()), "Price"]
    if not unit_price_series.empty:
        unit_price = unit_price_series.iloc[0]
        if pd.isna(row["Quantity"]) & pd.notna(row["Price"]):
            df.at[idx, "Quantity"] = row["Price"] / unit_price

---

##### Adding a new column Total Sales

In [36]:
df["Total_sales"] = df2["Quantity"] * df2["Price"]
df

NameError: name 'df2' is not defined